apiVersion: v1
kind: Namespace
metadata:
  name: dm-poc-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-poc-app
  namespace: dm-poc-app
spec:
  selector:
    matchLabels:
      name: dm-poc-app
  template:
    metadata:
      labels:
        name: dm-poc-app
    spec:
      containers:
      - name: app
        image: phelun/dm-app-1:0.1
        ports:
          - containerPort: 8080
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: dm-poc-app
  namespace: dm-poc-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    name: dm-poc-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dm-poc-app
  namespace: dm-poc-app
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dm-poc-app
            port:
              number: 80    
