name: fe-svc-build-pipeline

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: dm-poc-development
  # PROJECT_NUMBER: PROJECT_NUMBER

  CLUSTER: dm-poc-dev
  CLUSTER_ZONE: europe-west1

  REPOSITORY: dm-poc-development-image-reg
  REPOSITORY_REGION: europe-west1     
  IMAGE: dm-team-frontend-svc

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3      